/**
 * exportService.js — Generate PDF, PNG zip, and JSON exports
 */
const PDFDocument = require('pdfkit');
const archiver = require('archiver');
const path = require('path');
const fs = require('fs');
const projectStore = require('./projectStore');
const sceneStore = require('./sceneStore');
const shotStore = require('./shotStore');
const characterRefStore = require('./characterRefStore');
const locationRefStore = require('./locationRefStore');
const styleLockStore = require('./styleLockStore');
const scriptStore = require('./scriptStore');

const DATA_DIR = path.join(__dirname, '../../data/exports');

// Safe JSON parse — returns original value if already an object or if parsing fails
function safeParse(val, fallback = null) {
  if (val === null || val === undefined) return fallback;
  if (typeof val === 'object') return val;
  try { return JSON.parse(val); } catch { return fallback; }
}

// Ensure export directory exists
if (!fs.existsSync(DATA_DIR)) {
  fs.mkdirSync(DATA_DIR, { recursive: true });
}

/**
 * Generate a PDF storyboard
 */
async function generatePDF(projectId, settings = {}) {
  const project = projectStore.getProject(projectId);
  if (!project) throw new Error('Project not found');

  const scenes = sceneStore.listScenesByProject(projectId);
  const shots = shotStore.listShotsByProject(projectId);
  const layout = settings.layout || 'grid'; // 'grid' or 'single'
  const includeNotes = settings.includeNotes !== false;

  return new Promise((resolve, reject) => {
    const filename = `${project.title.replace(/[^a-zA-Z0-9]/g, '_')}_storyboard.pdf`;
    const filepath = path.join(DATA_DIR, filename);
    const doc = new PDFDocument({ size: 'A4', margin: 40 });
    const writeStream = fs.createWriteStream(filepath);

    doc.pipe(writeStream);

    // ─── Cover Page ─────────────────────────────────────────
    doc.fontSize(32).font('Helvetica-Bold').text(project.title, { align: 'center' });
    doc.moveDown();
    doc.fontSize(14).font('Helvetica').fillColor('#666')
      .text(`${scenes.length} Scenes · ${shots.length} Shots`, { align: 'center' });
    doc.moveDown();
    doc.fontSize(10).fillColor('#999')
      .text(`Generated by pucho.ai · ${new Date().toLocaleDateString()}`, { align: 'center' });
    doc.moveDown(2);

    if (project.style) {
      doc.fontSize(11).fillColor('#333').text(`Style: ${project.style}`, { align: 'center' });
    }

    // ─── Scene Pages ────────────────────────────────────────
    for (const scene of scenes) {
      doc.addPage();

      // Scene heading
      doc.fontSize(16).font('Helvetica-Bold').fillColor('#333')
        .text(`Scene ${scene.sceneNumber}: ${scene.heading || 'Untitled'}`, { underline: true });
      doc.moveDown(0.5);

      if (scene.location) {
        doc.fontSize(10).font('Helvetica').fillColor('#666')
          .text(`Location: ${scene.location}${scene.timeOfDay ? ` — ${scene.timeOfDay}` : ''}`);
      }

      if (scene.description && includeNotes) {
        doc.moveDown(0.3);
        doc.fontSize(9).fillColor('#555').text(scene.description, { width: 515 });
      }

      doc.moveDown();

      // Shots for this scene
      const sceneShots = shots.filter(s => s.sceneId === scene.id);

      if (layout === 'grid') {
        // Grid layout: 2 columns
        const colWidth = 250;
        const imgHeight = 140;
        let x = 40;
        let y = doc.y;

        for (let i = 0; i < sceneShots.length; i++) {
          const shot = sceneShots[i];

          if (y + imgHeight + 60 > doc.page.height - 40) {
            doc.addPage();
            y = 40;
          }

          // Shot image placeholder or embedded
          if (shot.imageUrl && shot.imageUrl.startsWith('data:image')) {
            try {
              const base64Data = shot.imageUrl.split(',')[1];
              const imgBuffer = Buffer.from(base64Data, 'base64');
              doc.image(imgBuffer, x, y, { width: colWidth, height: imgHeight, fit: [colWidth, imgHeight] });
            } catch {
              doc.rect(x, y, colWidth, imgHeight).fillColor('#f0f0f0').fill();
              doc.fontSize(8).fillColor('#999').text('Image unavailable', x + 80, y + 60);
            }
          } else {
            doc.rect(x, y, colWidth, imgHeight).fillColor('#f0f0f0').fill();
            doc.fontSize(8).fillColor('#999').text('No image', x + 100, y + 60);
          }

          // Shot info below image
          doc.fillColor('#333');
          doc.fontSize(9).font('Helvetica-Bold')
            .text(`Shot ${shot.shotNumber}`, x, y + imgHeight + 4, { width: colWidth });
          doc.font('Helvetica').fontSize(8).fillColor('#555')
            .text(shot.prompt || shot.description || '', x, y + imgHeight + 16, { width: colWidth, height: 30 });

          if (shot.cameraAngle) {
            doc.fontSize(7).fillColor('#888')
              .text(`📷 ${shot.cameraAngle}${shot.duration ? ` · ${shot.duration}s` : ''}`, x, y + imgHeight + 48, { width: colWidth });
          }

          // Move to next column or row
          if (i % 2 === 0) {
            x = 40 + colWidth + 15;
          } else {
            x = 40;
            y += imgHeight + 65;
          }
        }
      } else {
        // Single layout: full width
        for (const shot of sceneShots) {
          if (doc.y + 250 > doc.page.height - 40) doc.addPage();

          if (shot.imageUrl && shot.imageUrl.startsWith('data:image')) {
            try {
              const base64Data = shot.imageUrl.split(',')[1];
              const imgBuffer = Buffer.from(base64Data, 'base64');
              doc.image(imgBuffer, 40, doc.y, { width: 515, height: 280, fit: [515, 280] });
              doc.moveDown(0.5);
            } catch {
              doc.rect(40, doc.y, 515, 200).fillColor('#f0f0f0').fill();
              doc.moveDown(0.5);
            }
          }

          doc.y += 200;
          doc.fontSize(11).font('Helvetica-Bold').fillColor('#333')
            .text(`Shot ${shot.shotNumber}`);
          doc.fontSize(9).font('Helvetica').fillColor('#555')
            .text(shot.prompt || shot.description || '', { width: 515 });

          if (shot.cameraAngle || shot.cameraMovement) {
            doc.fontSize(8).fillColor('#888')
              .text(`Camera: ${shot.cameraAngle || ''} ${shot.cameraMovement ? '· ' + shot.cameraMovement : ''}`);
          }

          doc.moveDown();
        }
      }
    }

    doc.end();

    writeStream.on('finish', () => {
      resolve({ filename, filepath, url: `/exports/${filename}` });
    });
    writeStream.on('error', reject);
  });
}

/**
 * Generate PNG sequence as ZIP
 */
async function generatePNGSequence(projectId) {
  const project = projectStore.getProject(projectId);
  if (!project) throw new Error('Project not found');

  const shots = shotStore.listShotsByProject(projectId);
  const shotsWithImages = shots.filter(s => s.imageUrl && s.imageUrl.startsWith('data:image'));

  if (shotsWithImages.length === 0) {
    throw new Error('No shot images to export. Generate images first.');
  }

  const filename = `${project.title.replace(/[^a-zA-Z0-9]/g, '_')}_shots.zip`;
  const filepath = path.join(DATA_DIR, filename);

  return new Promise((resolve, reject) => {
    const output = fs.createWriteStream(filepath);
    const archive = archiver('zip', { zlib: { level: 6 } });

    output.on('close', () => {
      resolve({ filename, filepath, url: `/exports/${filename}`, fileCount: shotsWithImages.length, size: archive.pointer() });
    });

    archive.on('error', reject);
    archive.pipe(output);

    for (const shot of shotsWithImages) {
      const base64Data = shot.imageUrl.split(',')[1];
      const imgBuffer = Buffer.from(base64Data, 'base64');
      const ext = shot.imageUrl.includes('image/png') ? 'png' : 'jpg';
      const name = `shot_${String(shot.shotNumber).padStart(3, '0')}_scene_${shot.sceneId.slice(0, 8)}.${ext}`;
      archive.append(imgBuffer, { name });
    }

    archive.finalize();
  });
}

/**
 * Generate full project JSON export
 */
function generateProjectJSON(projectId) {
  const project = projectStore.getProject(projectId);
  if (!project) throw new Error('Project not found');

  const scenes = sceneStore.listScenesByProject(projectId);
  const shots = shotStore.listShotsByProject(projectId);
  const characters = characterRefStore.listByProject(projectId);
  const locations = locationRefStore.listByProject(projectId);
  const styleLock = styleLockStore.getByProject(projectId);

  let script = null;
  try {
    script = scriptStore.getScriptByProject(projectId);
  } catch { /* no script */ }

  const exportData = {
    version: '2.0',
    exportedAt: new Date().toISOString(),
    generator: 'pucho.ai StoryGen',
    project: {
      ...project,
      settings: safeParse(project.settings),
    },
    script: script ? {
      filename: script.filename,
      format: script.format,
      // Omit rawContent for smaller exports, include parsedContent
      parsedContent: safeParse(script.parsedContent),
    } : null,
    scenes: scenes.map(s => ({
      ...s,
      shots: shots.filter(sh => sh.sceneId === s.id).map(sh => ({
        ...sh,
        // Truncate base64 images in JSON export to keep file manageable
        imageUrl: sh.imageUrl && sh.imageUrl.startsWith('data:') ? '[base64-image]' : sh.imageUrl,
      })),
    })),
    consistency: {
      characters: characters.map(c => ({
        ...c,
        traits: safeParse(c.traits, {}),
        referenceImageUrl: c.referenceImageUrl && c.referenceImageUrl.startsWith('data:') ? '[base64-image]' : c.referenceImageUrl,
      })),
      locations: locations.map(l => ({
        ...l,
        traits: safeParse(l.traits, {}),
        referenceImageUrl: l.referenceImageUrl && l.referenceImageUrl.startsWith('data:') ? '[base64-image]' : l.referenceImageUrl,
      })),
      styleLock: styleLock ? {
        ...styleLock,
        extractedTraits: safeParse(styleLock.extractedTraits, {}),
      } : null,
    },
    stats: {
      sceneCount: scenes.length,
      shotCount: shots.length,
      imagesGenerated: shots.filter(s => s.imageUrl).length,
      characterCount: characters.length,
      locationCount: locations.length,
    },
  };

  const filename = `${project.title.replace(/[^a-zA-Z0-9]/g, '_')}_project.json`;
  const filepath = path.join(DATA_DIR, filename);
  fs.writeFileSync(filepath, JSON.stringify(exportData, null, 2));

  return { filename, filepath, url: `/exports/${filename}`, data: exportData };
}

/**
 * Import a project from JSON
 */
function importProjectJSON(jsonData) {
  if (!jsonData.project || !jsonData.version) {
    throw new Error('Invalid project JSON format');
  }

  // Create project
  const project = projectStore.createProject({
    title: jsonData.project.title + ' (Imported)',
    description: jsonData.project.description,
    style: jsonData.project.style,
    settings: jsonData.project.settings ? JSON.stringify(jsonData.project.settings) : null,
  });

  // Import scenes and shots
  if (jsonData.scenes) {
    for (const sceneData of jsonData.scenes) {
      const scene = sceneStore.createScene({
        projectId: project.id,
        sceneNumber: sceneData.sceneNumber,
        heading: sceneData.heading,
        location: sceneData.location,
        timeOfDay: sceneData.timeOfDay,
        description: sceneData.description,
        dialogue: sceneData.dialogue,
        notes: sceneData.notes,
        sortOrder: sceneData.sortOrder,
      });

      if (sceneData.shots) {
        for (const shotData of sceneData.shots) {
          shotStore.createShot({
            projectId: project.id,
            sceneId: scene.id,
            shotNumber: shotData.shotNumber,
            prompt: shotData.prompt,
            description: shotData.description,
            shotStory: shotData.shotStory,
            cameraAngle: shotData.cameraAngle,
            cameraMovement: shotData.cameraMovement,
            duration: shotData.duration,
            mood: shotData.mood,
            heroSubject: shotData.heroSubject,
            sortOrder: shotData.sortOrder,
          });
        }
      }
    }
  }

  // Import consistency data
  if (jsonData.consistency) {
    if (jsonData.consistency.characters) {
      for (const charData of jsonData.consistency.characters) {
        characterRefStore.create({
          projectId: project.id,
          name: charData.name,
          description: charData.description,
          traits: charData.traits,
        });
      }
    }

    if (jsonData.consistency.locations) {
      for (const locData of jsonData.consistency.locations) {
        locationRefStore.create({
          projectId: project.id,
          name: locData.name,
          description: locData.description,
          traits: locData.traits,
        });
      }
    }

    if (jsonData.consistency.styleLock) {
      styleLockStore.create({
        projectId: project.id,
        styleName: jsonData.consistency.styleLock.styleName,
        stylePrompt: jsonData.consistency.styleLock.stylePrompt,
        extractedTraits: jsonData.consistency.styleLock.extractedTraits,
      });
    }
  }

  return project;
}

module.exports = { generatePDF, generatePNGSequence, generateProjectJSON, importProjectJSON };
